2018-05-24 11:27:54,004 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 11:30:41,550 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:18:33,389 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:22:08,014 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:23:29,790 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:23:58,109 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:24:14,848 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:28:56,947 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:29:47,835 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:33:17,289 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:51:26,778 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-24 12:51:37,223 ERROR:             Exception on / [GET] [in /home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2018-05-24 15:56:26,112 ERROR:             Exception on / [GET] [in /home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/vishalan/Documents/home/FlaskAppV1/env/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2018-05-25 15:07:05,835 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-25 15:07:47,801 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
2018-05-25 15:11:41,273 INFO:             errors [in /home/vishalan/Documents/home/FlaskAppV1/flask_server/app.py:43]
